### ISSUE TITLE
Testing for chatbox

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-chatbox#5]

**Comment by oznekenzo** [comment]
- [x] Remove join button if only on web2
- [x] Input height
- [x] Move profile picture to first message
- [x] Click emoji should add to input
- [x] Change Ghost to "Chatbox"
- [x] Profile pic is centered, should be bottom aligned
- [x] send and emoji are centered, should be bottom aligned in input
- [x] Update icon
- [x] notification not working
- [x] If profile empty, add option to add profile, preferably with the correct web3 provider
- [x] Test not popup chat on mobile
- [x] change to following space
- [x] check documentation
- [x] emoji still sending as message
- [x] open in new tab if it goes to 3box
- [x] edit profile instead of update
- [x] message was showing above two emoji only messages
- [x] link to your own profile
